/* OwlPlug
 * Copyright (C) 2021 Arthur <dropsnorz@gmail.com>
 *
 * This file is part of OwlPlug.
 *
 * OwlPlug is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3
 * as published by the Free Software Foundation.
 *
 * OwlPlug is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OwlPlug.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.owlplug.parsers.reaper;

import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.util.ArrayList;
import java.util.List;

/**
 * A listener that walks a Reaper project parse tree and extracts VST plugin information.
 * This class implements the {@link ReaperProjectListener} interface generated by ANTLR.
 */
public class PluginNodeListener implements ReaperProjectListener {

    private List<ReaperPlugin> reaperPlugins = new ArrayList<>();

    /**
     * Returns the list of Reaper plugins found in the project.
     *
     * @return A list of {@link ReaperPlugin} objects.
     */
    public List<ReaperPlugin> getReaperPlugins() {
        return reaperPlugins;
    }

    @Override
    public void enterRoot(ReaperProjectParser.RootContext ctx) {
        // Not implemented
    }

    @Override
    public void exitRoot(ReaperProjectParser.RootContext ctx) {
        // Not implemented
    }

    /**
     * This method is called when the parser enters a node in the Reaper project tree.
     * It checks if the node represents a VST plugin, and if so, extracts the plugin's information
     * such as name, filename, and raw ID.
     *
     * @param ctx The context for the node.
     */
    @Override
    public void enterNode(ReaperProjectParser.NodeContext ctx) {

        // We are only interested in VST plugins, so we check the node name.
        if (!ctx.name().getText().equals("VST")) {
            return;
        }

        // Create a new ReaperPlugin object to store the plugin information.
        ReaperPlugin plugin = new ReaperPlugin();

        // The plugin name is the first value in the node.
        if (!ctx.value().isEmpty()) {
            // The name is quoted, so we remove the quotes.
            plugin.setName(ctx.value(0).getText().replaceAll("\"", ""));
        }

        // Extract second node positional parameter (filename)
        if (ctx.value().size() > 1) {
            plugin.setFilename(ctx.value(1).getText().replaceAll("\"", ""));
        }

        // The plugin raw ID is the fifth value in the node.
        if (ctx.value().size() > 4) {
            plugin.setRawId(ctx.value(4).getText());
        }

        // Add the plugin to the list of found plugins.
        reaperPlugins.add(plugin);

    }

    @Override
    public void exitNode(ReaperProjectParser.NodeContext ctx) {
        // Not implemented
    }

    @Override
    public void enterName(ReaperProjectParser.NameContext ctx) {
        // Not implemented
    }

    @Override
    public void exitName(ReaperProjectParser.NameContext ctx) {
        // Not implemented
    }

    @Override
    public void enterElement(ReaperProjectParser.ElementContext ctx) {
        // Not implemented
    }

    @Override
    public void exitElement(ReaperProjectParser.ElementContext ctx) {
        // Not implemented
    }

    @Override
    public void enterLeaf(ReaperProjectParser.LeafContext ctx) {
        // Not implemented
    }

    @Override
    public void exitLeaf(ReaperProjectParser.LeafContext ctx) {
        // Not implemented
    }

    @Override
    public void enterValue(ReaperProjectParser.ValueContext ctx) {
        // Not implemented
    }

    @Override
    public void exitValue(ReaperProjectParser.ValueContext ctx) {
        // Not implemented
    }

    @Override
    public void enterProp(ReaperProjectParser.PropContext ctx) {
        // Not implemented
    }

    @Override
    public void exitProp(ReaperProjectParser.PropContext ctx) {
        // Not implemented
    }

    @Override
    public void visitTerminal(TerminalNode terminalNode) {
        // Not implemented
    }

    @Override
    public void visitErrorNode(ErrorNode errorNode) {
        // Not implemented
    }

    @Override
    public void enterEveryRule(ParserRuleContext parserRuleContext) {
        // Not implemented
    }

    @Override
    public void exitEveryRule(ParserRuleContext parserRuleContext) {
        // Not implemented
    }
}
